config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home', to: 'home#index'
  get 'search/:key/:value', to: 'search#apartment_search', as: :apartment_search
  get 'search', to: 'search#filter_search', as: :search
  resources :apartments, only: [:show, :index]
end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show]

  def index
    @apartments = Apartment.all.paginate(page: params[:page])
  end

  def show
  end

  private
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def apartment_search
    @apartments = Apartment.where(search_param).paginate(page: params[:page])
    render 'apartments/index'
  end

  def filter_search
    render params[:filter]
  end

  private
    def search_param
      { params[:key] => params[:value] }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Address line1</th>
      <th>Address line2</th>
      <th>Description</th>
      <th>Bedrooms</th>
      <th>Bathrooms</th>
      <th>Parking</th>
      <th>Gym</th>
      <th>Price</th>
      <th>Address suburb</th>
      <th>Address postcode</th>
      <th>Address state</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.address_line1 %></td>
        <td><%= apartment.address_line2 %></td>
        <td><%= apartment.description %></td>
        <td><%= apartment.bedrooms %></td>
        <td><%= apartment.bathrooms %></td>
        <td><%= apartment.parking %></td>
        <td><%= apartment.gym %></td>
        <td><%= apartment.price %></td>
        <td><%= apartment.address_suburb %></td>
        <td><%= apartment.address_postcode %></td>
        <td><%= apartment.address_state %></td>
        <td><%= link_to 'Show', apartment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @apartments %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address line1:</strong>
  <%= @apartment.address_line1 %>
</p>

<p>
  <strong>Address line2:</strong>
  <%= @apartment.address_line2 %>
</p>

<p>
  <strong>Description:</strong>
  <%= @apartment.description %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @apartment.bedrooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @apartment.bathrooms %>
</p>

<p>
  <strong>Parking:</strong>
  <%= @apartment.parking %>
</p>

<p>
  <strong>Gym:</strong>
  <%= @apartment.gym %>
</p>

<p>
  <strong>Price:</strong>
  <%= @apartment.price %>
</p>

<p>
  <strong>Address suburb:</strong>
  <%= @apartment.address_suburb %>
</p>

<p>
  <strong>Address postcode:</strong>
  <%= @apartment.address_postcode %>
</p>

<p>
  <strong>Address state:</strong>
  <%= @apartment.address_state %>
</p>

<%= link_to 'Back', apartments_path %>

app/views/home/index.html.erb
<h1>Apartmonty</h1>
Looking for a new apartment? Australia's #1 Apartment site, featuring the best stock is <i>Apartmonty.</i>

<ul>
<li><%= link_to 'Recent apartments', search_path(filter: :recent) %></li>
<li><%= link_to 'Bargain two bedroom apartments', apartment_search_path(:bedrooms, 2) %></li>
<li><%= link_to 'The Top Shelf', search_path(filter: :top_shelf) %></li>
<li><%= link_to 'Everything', apartments_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apartmonty</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/recent.html.erb
<h1>Recent apartments</h1>
<% @apartments = Apartment.order(:updated_at).paginate(page: params[:page]) %>
<table>
<tr>
  <th>Address</th>
  <th>Price</th>
  <th>Last updated</th>
</tr>

<% @apartments.each do |apartment| %>
  <tr>
    <td><%= apartment.address_line1%> <%= apartment.address_line2 %></td>
    <td><%= apartment.price %></td>
    <td><%= apartment.updated_at %></td>
<% end %>

</table>

<br/>
<%= will_paginate @apartments %>

app/views/search/top_shelf.html.erb
<h1>The Top Shelf</h1>